# Generated by Django 6.0.4 on 2026-04-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_chat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
