# Generated by Django 6.0.4 on 2026-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chunk_overlap',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chunk_size',
            field=models.IntegerField(default=1500),
        ),
    ]
