# Generated by Django 6.0.4 on 2026-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_conversation_chunk_overlap_conversation_chunk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecitation',
            name='end_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecitation',
            name='start_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
