# Generated by Django 6.0.4 on 2026-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_messagecitation_end_line_messagecitation_start_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecitation',
            name='citation_marker',
            field=models.CharField(blank=True, help_text='Ví dụ: 【1†L5-L8】', max_length=50),
        ),
    ]
