# Generated by Django 6.0.4 on 2026-04-18 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_messagecitation_citation_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('start_index', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='models.conversation')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='models.file')),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
    ]
