# Generated by Django 6.0.4 on 2026-04-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_conversation_last_chat_at'),
        ('models', '0005_chunk'),
    ]

    operations = [
    ]
