# Generated by Django 6.0.4 on 2026-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_merge_0002_conversation_last_chat_at_0005_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecitation',
            name='graph_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagecitation',
            name='graph_entity_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecitation',
            name='graph_entity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
