# Generated by Django 6.0.4 on 2026-04-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_messagecitation_graph_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecitation',
            name='content_chunk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='models.file'),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
