# Generated by Django 6.0.4 on 2026-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_messagecitation_content_chunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecitation',
            name='citation_marker',
            field=models.CharField(blank=True, help_text='Ví dụ: 【1†L5-L8】', max_length=100),
        ),
    ]
