# Generated by Django 6.0.4 on 2026-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_messagecitation_citation_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecitation',
            name='citation_marker',
            field=models.TextField(blank=True, help_text='Ví dụ: 【1†L5-L8】'),
        ),
        migrations.AlterField(
            model_name='messagecitation',
            name='graph_entity_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
